### ISSUE TITLE
Consider adding a variant without bold fonts

### ISSUE THREAD

**Issue by Soupertonic** [mikesun/msun-dark-zed#1]
I love the theme but I'm not a fan of the bold markings popping out in the syntax highlighting.

**Comment by mikesun** [comment]
Good suggestion, will do!

**Comment by mikesun** [comment]
https://github.com/mikesun/msun-dark-zed/commit/88b355acee449b6725ca231f1881423c36387376 adds variants with no bold style on syntax.

https://github.com/zed-industries/extensions/pull/115 will update the Zed extension
