### ISSUE TITLE
Unstage git files

### ISSUE THREAD

**Issue by GEREGUR** [mikesun/msun-dark-zed#2]
Hi! I really felt in love with your theme and there are not anything even close to it. But I have a problem with git unstaged files -> their names just dissapear

here im using  msun-dark
<img width="1440" alt="ScreenShot 2024-08-04 at 18 04 52" src="https://github.com/user-attachments/assets/b23b0989-ff8c-4b0c-8903-498e8d574921">

and here is an example of another theme
<img width="1440" alt="ScreenShot 2024-08-04 at 18 05 38" src="https://github.com/user-attachments/assets/16551aac-3443-4ca1-9e19-8bdff729a025">

Ive tried to fix it by myseld using 
"experimental.theme_overrides"
but there are to many options for me to look through to find the issue

**Comment by mikesun** [comment]
Oh nice find! I don't normally have `"git_status"` enabled so I haven't run into this. Lemme take a look at get you a quick fix and then I'll update the theme

**Comment by mikesun** [comment]
> Ive tried to fix it by myseld using "experimental.theme_overrides" but there are to many options for me to look through to find the issue

Try:
```json
  "experimental.theme_overrides": {
    "created": "#ccffe6",
    "conflict": "#f98f86",
    "modified": "#b3d5ff",
    "info": "#b3d5ff"
  }
```

**Comment by GEREGUR** [comment]
Yes! That worked, thank you so much!

**Comment by GEREGUR** [comment]
Hi again! Hope that doesnt annoy u at all, but after the update the 6000k theme (which is my favourite) just dissapeared
<img width="1440" alt="ScreenShot 2024-08-05 at 19 42 01" src="https://github.com/user-attachments/assets/61e408f0-526b-4572-8951-b60fe1651800">

**Comment by mikesun** [comment]
Ah, yeah I had taken it out... I'll add it back

**Comment by mikesun** [comment]
https://github.com/zed-industries/extensions/pull/1209
